### ISSUE TITLE
0.14.1 Compilation error on file lib/dynamo/connection/query_parser.ex

### ISSUE THREAD

**Issue by namxam** [dynamo/dynamo#239]
Cannot compile it with elixir 0.14.1

```
== Compilation error on file lib/dynamo/connection/query_parser.ex ==
** (CompileError) lib/dynamo/connection/query_parser.ex:2: undefined function defexception/2
    (elixir) src/elixir.erl:188: :elixir.quoted_to_erl/3
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:156: :elixir.erl_eval/2
```

**Comment by stevedomin** [comment]
I've fixed these, but there's still a handful of specs not passing with the 0.14.x branch

**Comment by mcfiredrill** [comment]
Getting the same issue on 0.14.2.

**Comment by rozap** [comment]
Anyone still getting this? On master 0.14.3 i get this after attempting to start a dynamo project.

**Comment by habuka036** [comment]
I'm faced this issue with 0.14.4-dev.

**Comment by mikebarb** [comment]
Got the same error with Elixir (0.14.1)

Downloaded dynamo last night.
Mix file for downloaded dynamo contains:
  def project do
    [ app: :dynamo,
      elixir: "~> 0.13.3 or ~> 0.14.0-dev",
      version: "0.1.0-dev",
      name: "Dynamo",
      source_url: "https://github.com/dynamo/dynamo",
      deps: deps(Mix.env),
      docs: &docs/0 ]
  end

**Comment by sportsmithshelby** [comment]
Same mix.exs as above.

Elixir 0.14.3-dev

MIX_ENV=test mix do deps.get, test

== Compilation error on file lib/dynamo/connection/query_parser.ex ==
*\* (CompileError) lib/dynamo/connection/query_parser.ex:2: undefined function defexception/2
    (elixir) src/elixir.erl:202: :elixir.quoted_to_erl/3
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:170: :elixir.erl_eval/3

If I apply a kluge to get past this error, I get lots of other errors in other files regarding undefined functions, like integer_to_binary and binary_to_integer.

**Comment by dgbc** [comment]
Same issue on 0.15.2-dev

== Compilation error on file lib/dynamo/connection/query_parser.ex ==
*\* (CompileError) lib/dynamo/connection/query_parser.ex:2: undefined function defexception/2
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (elixir) src/elixir_exp.erl:49: :elixir_exp.expand/2
    (elixir) src/elixir.erl:206: :elixir.quoted_to_erl/3
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:175: :elixir.erl_eval/3

**Comment by rosscdh** [comment]
+1 same here (Elixir 0.14.2)

**Comment by s3k** [comment]
Yep, Elixir 0.15.1

== Compilation error on file lib/dynamo/connection/query_parser.ex ==
*\* (CompileError) lib/dynamo/connection/query_parser.ex:2: undefined function defexception/2
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (elixir) src/elixir_exp.erl:49: :elixir_exp.expand/2
    (elixir) src/elixir.erl:206: :elixir.quoted_to_erl/3
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:175: :elixir.erl_eval/3

**Comment by s3k** [comment]
Ok, tried to find out what the problem is.
To many deprecations in version 0.15.1 

`size, defexception, list_to_tuple, binary_to_integer`

**Comment by dankozlowski** [comment]
Is there progress being made here, or should those of us working on >v0.15 just use something else?
