### ISSUE TITLE
Can't compile Dynamo

### ISSUE THREAD

**Issue by guilleiguaran** [dynamo/dynamo#176]
Currently I'm getting this while I try to compile Dynamo:

```
~/code/dynamo[master] % MIX_ENV=test mix do deps.get, test  
All dependencies up to date
Compiled lib/dynamo/app.ex
Compiled lib/dynamo/base.ex
Compiled lib/dynamo/connection/behaviour.ex
Compiled lib/dynamo.ex
Compiled lib/binary/dict.ex
== Compilation error on file lib/dynamo/connection/query_parser.ex ==
** (CompileError) lib/dynamo/connection/query_parser.ex:88: function current/0 undefined
    lists.erl:1323: :lists.foreach/2
    erl_eval.erl:569: :erl_eval.do_apply/6
    src/elixir.erl:140: :elixir.eval_forms/4
    src/elixir_lexical.erl:17: :elixir_lexical.run/2
```

I'm using Elixir master (0.12.2-dev) and Erlang R16B03 under OS X 10.9

Let me know if I can provide any other info that can be useful to fix this.

**Comment by devinus** [comment]
@guilleiguaran This has to do with the fact that Elixir doesn't export vars outside of the scope of the case.

https://github.com/dynamo/dynamo/blob/master/lib/dynamo/connection/query_parser.ex#L82

That line should be:

``` elixir
current = case Binary.Dict.get(acc, key, []) do
```

**Comment by guilleiguaran** [comment]
Just tested using other Elixir versions, it works fine with 0.12.0 and 0.12.1, but in 0.12.1 I'm getting some warnings:

```
lib/dynamo/connection/query_parser.ex:90: variable current is defined in a case clause and is unsafe, please assign it explicitly
lib/dynamo/connection/query_parser.ex:88: variable current is defined in a case clause and is unsafe, please assign it explicitly
```

So I guess that is the reason

**Comment by guilleiguaran** [comment]
@devinus thanks for your quick reply!!!

Just tested your suggestion and it's now working fine, I've created a PR for it: #177

**Comment by devinus** [comment]
Thank you!
